name: Continuous Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Runs a single command using the runners shell
      - name: Installing Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: Installing surge
        run: npm install --global surge
      - name: deploying using surge
