  
name: Continuous Deployment
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - run: echo "Setting up NodeJs"
            - name: Setup NodeJs
              uses: actions/setup-node@v1
              with:
               node-version: 12.x

            - run: npm install -g surge
            - run: echo "Deploying website"
            - run: surge ./ http://bootcamp2020-class1sample.surge.sh --token ${{ secrets.SURGE_TOKEN }} 
          
            - run: echo "Please visit => http://bootcamp2020-class1sample.surge.sh/"
